//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThidasaAssignemnt.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkill
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> SkillId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
